export const DOCTOR_FETCH_ALL = "DOCTOR_FETCH_ALL";

export const USER_FETCH = "USER_FETCH";
export const USER_FETCH_PENDING = "USER_FETCH_PENDING";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";
export const USER_RESET = "USER_RESET";
export const USER_UPDATE_AVATAR = "USER_UPDATE_AVATAR";

export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const FETCH_PROPERTY_PENDING = "FETCH_PROPERTY_PENDING";
export const FETCH_PROPERTY_ERROR = "FETCH_PROPERTY_ERROR";

export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const FETCH_SERVICES_PENDING = "FETCH_SERVICES_PENDING";
export const FETCH_SERVICES_ERROR = "FETCH_SERVICES_ERROR";
export const UPDATE_WIDTH = "UPDATE_WIDTH";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";

export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const UPDATE_BACKGROUND = "UPDATE_BACKGROUND";

export const SET_LAST_PET = "SET_LAST_PET";
